"""Tests for the Alembic migration path.

The rest of the suite builds its throwaway schema straight from
`SQLModel.metadata`, which is far faster than migrating per test. These tests
cover what a real deployment actually runs, and — via
`test_models_and_migrations_agree` — are what makes that shortcut safe.
"""

import logging
import sqlite3
from collections.abc import Generator
from pathlib import Path

import pytest
from alembic.config import Config

from alembic import command
from app.config import get_settings
from app.db import ALEMBIC_INI, get_engine, init_db, run_migrations


@pytest.fixture(name="fresh_db")
def fresh_db_fixture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> Generator[Path, None, None]:
    """Point the process-wide settings at an empty database file.

    Unlike the session-scoped isolation fixture, this gives each test a
    database with no schema at all, which is the state a migration has to
    cope with.
    """
    db_path = tmp_path / "migrate.db"
    monkeypatch.setenv("LIBRA_DATABASE_URL", f"sqlite:///{db_path}")
    get_settings.cache_clear()
    get_engine.cache_clear()
    yield db_path
    get_engine().dispose()
    get_settings.cache_clear()
    get_engine.cache_clear()


def _tables(db_path: Path) -> set[str]:
    with sqlite3.connect(db_path) as conn:
        rows = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
        return {row[0] for row in rows}


def _columns(db_path: Path, table: str) -> set[str]:
    with sqlite3.connect(db_path) as conn:
        return {row[1] for row in conn.execute(f"PRAGMA table_info({table})")}


def test_migrations_create_the_schema(fresh_db: Path) -> None:
    run_migrations()

    assert "book" in _tables(fresh_db)
    assert _columns(fresh_db, "book") == {
        "id",
        "title",
        "author",
        "format",
        "file_path",
        "year",
        "blurb",
        "pages",
        "uploaded_by",
        "book_metadata",
    }
    assert {"user_book_state", "note"} <= _tables(fresh_db)


def test_reading_state_is_keyed_by_user_and_book(fresh_db: Path) -> None:
    """The composite key is load-bearing: it makes the lazy upsert a single
    primary-key lookup, and in #7 it is what makes 'one shelf per user per
    book' structural rather than a constraint something has to enforce."""
    run_migrations()

    with sqlite3.connect(fresh_db) as conn:
        key = [row[1] for row in conn.execute("PRAGMA table_info(user_book_state)") if row[5]]

    assert sorted(key) == ["book_id", "user_id"]


def test_migrations_record_their_version(fresh_db: Path) -> None:
    """Without a stamped version, the next upgrade would re-run from scratch."""
    run_migrations()

    assert "alembic_version" in _tables(fresh_db)


def test_migrations_are_idempotent(fresh_db: Path) -> None:
    """Every app start runs them, so a second run must be a no-op, not an error."""
    run_migrations()
    run_migrations()

    assert "book" in _tables(fresh_db)


def test_models_and_migrations_agree(fresh_db: Path) -> None:
    """Fail if a model changed without a matching migration.

    This is the guard that makes the rest of Phase 1 safe. Every remaining
    milestone adds columns, `create_all()` no longer runs in the app, and
    SQLModel would happily let a model drift ahead of the schema — surfacing
    only as an OperationalError at runtime, against whichever query touched
    the missing column first.
    """
    run_migrations()

    config = Config(ALEMBIC_INI)
    with get_engine().begin() as connection:
        config.attributes["connection"] = connection
        # Raises AutogenerateDiffsDetected when the models imply schema
        # changes no revision covers.
        command.check(config)


def test_migrations_do_not_depend_on_the_working_directory(
    fresh_db: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Migrations must run from wherever the process happens to start.

    The Docker image sets WORKDIR /app and starts uvicorn there, not in the
    directory holding alembic.ini. If either the config path or
    `script_location` were resolved against the cwd, containers would start
    and immediately fail — a break that no test running from the repo root
    would ever notice.
    """
    elsewhere = tmp_path / "elsewhere"
    elsewhere.mkdir()
    monkeypatch.chdir(elsewhere)

    run_migrations()

    assert "book" in _tables(fresh_db)


def test_migrations_leave_application_logging_alone(fresh_db: Path) -> None:
    """Running migrations must not switch off the app's own loggers.

    `fileConfig` defaults to `disable_existing_loggers=True`, which disables
    every logger not named in alembic.ini. Since migrations run inside the
    startup lifespan, uvicorn has already configured `uvicorn.access` and
    `uvicorn.error` by then — so the default would silently kill access and
    error logging for the whole life of the process, in production only,
    with nothing in the output to say why.
    """
    access_log = logging.getLogger("uvicorn.access")
    access_log.disabled = False

    run_migrations()

    assert not access_log.disabled


def test_auto_upgrade_can_be_disabled(fresh_db: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The escape hatch for running migrations as a separate deploy step."""
    monkeypatch.setenv("LIBRA_AUTO_UPGRADE_DB", "false")
    get_settings.cache_clear()

    init_db()

    assert "book" not in _tables(fresh_db)
