"""add reading position to user_book_state

Revision ID: 8be05e88e049
Revises: 12214bf85cad
Create Date: 2026-09-03 22:31:48.427774

"""

from collections.abc import Sequence

import sqlalchemy as sa

# Autogenerate renders SQLModel's string columns as
# `sqlmodel.sql.sqltypes.AutoString()` but does not add this import itself,
# so every generated migration would fail with a NameError without it.
# Unused in migrations that touch no string column; hence the noqa.
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8be05e88e049"
down_revision: str | Sequence[str] | None = "12214bf85cad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_book_state", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("position", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_book_state", schema=None) as batch_op:
        batch_op.drop_column("position")

    # ### end Alembic commands ###
