"""tags

Revision ID: 9a8d5d47149e
Revises: afb8fd54343f
Create Date: 2026-08-08 22:45:59.846146

"""

from collections.abc import Sequence

import sqlalchemy as sa

# Autogenerate renders SQLModel's string columns as
# `sqlmodel.sql.sqltypes.AutoString()` but does not add this import itself,
# so every generated migration would fail with a NameError without it.
# Unused in migrations that touch no string column; hence the noqa.
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a8d5d47149e"
down_revision: str | Sequence[str] | None = "afb8fd54343f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(collation="NOCASE"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tag_global_name", ["name"], unique=True, sqlite_where=sa.text("owner_id IS NULL")
        )
        batch_op.create_index(batch_op.f("ix_tag_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index("ix_tag_owner_name", ["owner_id", "name"], unique=True)

    op.create_table(
        "book_tag",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("book_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_tag")
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_index("ix_tag_owner_name")
        batch_op.drop_index(batch_op.f("ix_tag_owner_id"))
        batch_op.drop_index("ix_tag_global_name", sqlite_where=sa.text("owner_id IS NULL"))

    op.drop_table("tag")
    # ### end Alembic commands ###
