"""shelves

Revision ID: afb8fd54343f
Revises: 69e4f2dbef24
Create Date: 2026-08-08 22:20:18.585647

"""

from collections.abc import Sequence

import sqlalchemy as sa

# Autogenerate renders SQLModel's string columns as
# `sqlmodel.sql.sqltypes.AutoString()` but does not add this import itself,
# so every generated migration would fail with a NameError without it.
# Unused in migrations that touch no string column; hence the noqa.
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afb8fd54343f"
down_revision: str | Sequence[str] | None = "69e4f2dbef24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

FK_STATE_SHELF = "fk_user_book_state_shelf_id_shelf"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shelf",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(collation="NOCASE"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shelf", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shelf_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index("ix_shelf_owner_name", ["owner_id", "name"], unique=True)

    # Named explicitly: autogenerate emits `create_foreign_key(None, ...)`, and
    # batch mode — which SQLite always uses here — rejects an unnamed
    # constraint. The downgrade needs the same name to drop it.
    with op.batch_alter_table("user_book_state", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shelf_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(FK_STATE_SHELF, "shelf", ["shelf_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_book_state", schema=None) as batch_op:
        batch_op.drop_constraint(FK_STATE_SHELF, type_="foreignkey")
        batch_op.drop_column("shelf_id")

    with op.batch_alter_table("shelf", schema=None) as batch_op:
        batch_op.drop_index("ix_shelf_owner_name")
        batch_op.drop_index(batch_op.f("ix_shelf_owner_id"))

    op.drop_table("shelf")
    # ### end Alembic commands ###
